name: Build

env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1    
    
on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0    

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: ConsoleBox
      working-directory: src/Console/src
      run: |
        echo Basic, Serilog, Async
        dotnet build /p:DefineConstants=basic%3Bserilog%3Basync
        echo Basic, Serilog
        dotnet build /p:DefineConstants=basic%3Bserilog
        echo Basic
        dotnet build /p:DefineConstants=basic
        echo Basic, Async
        dotnet build /p:DefineConstants=basic%3Basync
        echo Serilog
        dotnet build /p:DefineConstants=serilog
        echo Serilog, Async
        dotnet build /p:DefineConstants=serilog%3Basync
        echo Async
        dotnet build /p:DefineConstants=async
        echo None
        dotnet build 

    - name: WebApiBox
      working-directory: src/WebApi/src
      run: |
        echo appSettings
        dotnet build -nologo -c:Release /p:DefineConstants=appSettings
        echo openApi
        dotnet build -nologo -c:Release /p:DefineConstants=openApi
        echo windowsService
        dotnet build -nologo -c:Release /p:DefineConstants=windowsService
        echo exceptionMiddleware
        dotnet build -nologo -c:Release /p:DefineConstants=exceptionMiddleware
        echo elasticLog
        dotnet build -nologo -c:Release /p:DefineConstants=elasticLog
        echo appSettings elasticLog
        dotnet build -nologo -c:Release /p:DefineConstants=appSettings%3BelasticLog
        echo None
        dotnet build -nologo -c:Release 

    - name: Version
      run: |  
        dotnet tool install --global GitVersion.Tool --version 5.8.1
        dotnet gitversion /output buildserver 
        
    - name: Pack
      run: nuget pack .nuspec -NoDefaultExcludes -OutputDirectory bin -Version ${{ env.GitVersion_FullSemVer }}
 
