name: NuGet

on:
  push:
     tags: '*'

env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    
jobs:
  nuget:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1      
      with:
        dotnet-version: 8.0.x
    
    - name: ConsoleBox
      working-directory: src/Console/src
      run: |
        echo --basic --serilog -async
        dotnet build /p:DefineConstants=basic%3Bserilog%3Basync
        echo --basic --serilog
        dotnet build /p:DefineConstants=basic%3Bserilog
        echo --basic
        dotnet build /p:DefineConstants=basic
        echo --basic --sync
        dotnet build /p:DefineConstants=basic%3Basync
        echo --serilog
        dotnet build /p:DefineConstants=serilog
        echo --serilog --async
        dotnet build /p:DefineConstants=serilog%3Basync
        echo --async
        dotnet build /p:DefineConstants=async
        echo none
        dotnet build 

    - name: WebApiBox
      working-directory: src/WebApi/src
      run: |
        echo none
        dotnet build -nologo -c:Release 
        echo --name-override
        dotnet build -nologo -c:Release /p:DefineConstants=nameOverride
        echo --windows-service
        dotnet build -nologo -c:Release /p:DefineConstants=windowsService
        echo --exceptionMiddleware
        dotnet build -nologo -c:Release /p:DefineConstants=exceptionMiddleware
        echo --elasticLog
        dotnet build -nologo -c:Release /p:DefineConstants=elasticLog
        echo --name-override --elasticLog
        dotnet build -nologo -c:Release /p:DefineConstants=nameOverride%3BelasticLog
        echo --nameOverride --elasticLog --exceptionMiddleware --windows-service --name-override
        dotnet build -nologo -c:Release /p:DefineConstants=nameOverride%3BelasticLog%3BexceptionMiddleware%3BwindowsService%3BnameOverride%3B

    - name: LibraryBox
      working-directory: src/Library/src
      run: |
        echo build
        dotnet build 
        # Cannot pack due to license properties in project file

    - name: Version
      run: |  
        dotnet tool install --global GitVersion.Tool --version 6.0.4
        dotnet gitversion /output buildserver 
        
    - name: Update
      run: |
        HEADER="Created with JandaBox"
        REPLACEMENT="$HEADER ${{ env.GitVersion_FullSemVer }}"
        find . -type f -name "Program.cs" -exec sed "s/$HEADER/$REPLACEMENT/g" {} +
        find . -type f -name "Program.cs" -exec sed -i "s/$HEADER/$REPLACEMENT/g" {} +

    - name: Pack
      run: nuget pack .nuspec -NoDefaultExcludes -OutputDirectory bin -Version ${{ env.GitVersion_SemVer }}
          
    - name: Push    
      run: dotnet nuget push "bin/*.nupkg" -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
