name: NuGet

on:
  push:
     tags: '*'

env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    
jobs:
  nuget:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1      
      with:
        dotnet-version: 7.0.x
    
    - name: ConsoleBox
      working-directory: src/Console/src
      run: |
        dotnet build -nologo -c:Release

    - name: Version
      run: |  
        dotnet tool install --global GitVersion.Tool --version 5.8.1
        dotnet gitversion /output buildserver 
        
    - name: Pack
      run: nuget pack .nuspec -NoDefaultExcludes -OutputDirectory bin -Version ${{ env.GitVersion_SemVer }}
 
    - name: Push    
      run: dotnet nuget push "bin/*.nupkg" -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
